project_id = "bsmujjrfwyqlfdqnjpes"

[functions.send-wholesale-inquiry]
verify_jwt = false

[functions.admin-auth]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.printify]
verify_jwt = false

[functions.merch-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
